const oneLiners = [
    "For you the bells toll!",
    "Your time has come!",
    "The bell tolls for thee!",
    "The end is nigh!",
    "Your fate is sealed!",
    "The hour of reckoning is at hand!",
    "Your destiny awaits!",
    "The tolling bell is your death knell!",
    "Your time on this earth is up!",
    "The bell tolls, and you shall answer!",
    "Your end is written in the stars!",
    "The time has come to pay the price!",
    "The tolling of the bell is the harbinger of your doom!",
    "Your sins have caught up to you!",
    "The bell tolls, and your fate is sealed!",
    "The reckoning has arrived!",
    "The end is near!",
    "Your time is up!",
    "The bell tolls for all, but it tolls loudest for you!",
    "You have been weighed, you have been measured, and you have been found wanting!",
    "Your time has run out!",
    "The end is inevitable!",
    "The bell tolls, and so it begins!",
    "Your fate is inescapable!",
    "The hourglass has run out of sand for you!",
    "The bell tolls, and death comes for you!",
    "Your time has expired!",
    "The end is written, and you cannot change it!",
    "The tolling of the bell is the last thing you'll hear!",
    "Your time is done!",
    "The end has come!",
    "The bell tolls, and your fate is sealed!",
    "Your fate was decided long ago!",
    "The reckoning has come!",
    "The bell tolls, and the end is near!",
    "Your time has come to an end!",
    "The end is here!",
    "The tolling of the bell is the sound of your demise!",
    "Your time on this world is finished!",
    "The end is written in the stars!",
    "The bell tolls, and so it shall be!",
    "Your destiny is sealed!",
    "The hour of your death is at hand!",
    "The tolling of the bell marks the end of your life!",
    "Your end is inevitable!",
    "The bell tolls, and it tolls for you!",
    "Your time has come to face the music!",
    "The end is upon you!",
    "The bell tolls, and you cannot escape your fate!",
    "Your time on this earth is at an end!",
    "The end is near, and you cannot run from it!",
    "The tolling of the bell is the sound of your doom!",
    "Your fate is sealed, and the bell tolls for you!"
];


let spkr = ChatMessage.getSpeaker({ actor: actor });
ChatMessage.create({
    speaker: spkr,
    content: oneLiners[Math.floor(Math.random() * oneLiners.length)],
    type: CONST.CHAT_MESSAGE_TYPES.EMOTE
},
    { chatBubble: true });

item.use();